adx_append: true
adx_appendto: true
adx_create: true
adx_delete: true
adx_entitylogicalname: cr6fc_wcapplications
adx_entityname: WCApplications
adx_entitypermission_webrole:
- 3069438b-c2f9-442b-9d11-3e42a4cb8a6b
- 691626fe-bf7a-4753-89e5-5bba3a6e7c24
- 9b3d22e4-2339-413e-b753-7c71791a03b1
adx_entitypermissionid: 675b93b3-927c-ef11-ac21-002248d62002
adx_read: true
adx_scope: 756150000
adx_write: true
